---
title: 
  "Empirische Bildungsforschung"
---

Hallo und herzlich willkommen,

auf der Lehrveranstaltungseite Einführung in die empirische Bildungsforschung (Stand: Sommersemester 2021). Auf der Seite findest für jede Sitzung das Lernmodul, die Module als PDFs, ein paar Vorabinfos zum Inhalt sowie Lernzielfragen mit denen du überprüfen kannst ob du die zentralen Inhalte verstanden hast. Ebenso kannst du dir das <a href="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5234058/index.html#/" target="_blank">Programm</a> der LV herunterladen.

In der ersten Sitzung am 15.03.2021 werden wir alles zum Thema Ablauf der Lehrveranstaltung klären, bis dahin kannst du dir das erste Lernmodul anschauen oder im Programm stöbern.

Wenn du noch weitere Fragen hast, kannst du deine Frage auf Studon posten, mich direkt anschreiben, oder den Chatbot der Lehrveranstaltung fragen. Edgar Bot weiß nicht alles, er wurde aber gefüttert mit den Basic Facts der Vorlesung, zeigt in welchem Modul ein Thema behandelt wurde und kennt die formalen Anforderungen des Kurses.  
