---
title: "Session 03"
---

```{r, echo=FALSE}
library(fontawesome)
```


### `r fa("info", fill = "darkgray")` Info

- Session 3 gibt einen Überblick über die Ziele der Bildungsforschung.
- Als empirisch fundierte Wissenschaft, werden Bildungsvorgänge möglichst präzise beschrieben, empirisch prüfbare Theorien werden zur Erklärung herangezogen, sowie darauf aufbauen Prognosen abgeleitet.
- Dies wird am Beispiel Geschlechtereffekte in der Bildungsforschung herausgearbeitet.
- Abschließend erfolgt ein kurzer Abriss zum Thema Messung von Bildung. 


### `r fa("newspaper", fill = "darkgray")`  Lernmodul

 <iframe src="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5280198/index.html" width="100%" height="400" style="border:border:1px solid black;" allow="fullscreen">
</iframe>

- Mouse click inside the slide and press F for the full picture mode
- <a href="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5234058/index.html#/" target="_blank">Or open in a new tab!</a>



### `r fa("question", fill = "darkgray")` Lernzielfrage(n)

- Kannst du die Ziele der Bildungsforschung an einem anderen Thema erklären? (Bsp. Bildungserfolg von Personen mit Migrationshintergrund)
- Warum braucht die EBF die Coleman'sche Badewanne?
- Was bedeutet die Raschkonformität und wie könnte sie geprüft werden?

### `r fa("file-pdf", fill = "darkgray")` Materialien

<a href="https://www.studon.fau.de/file3797632_download.html" class="btn btn-secondary"> Slides</a>








