---
title: "Session 02"
---

```{r, echo=FALSE}
library(fontawesome)
```


### `r fa("info", fill = "darkgray")` Info

- Session 2 richtet sich an Personen mit geringerem statistischen Vorwissen und führt in die lineare Regression ein.
- Neben der Grundidee einer linearen Regression wird die Methode der kleinsten Quadrate eingeführt und R² als Maß zur Beurteilung der Güte erklärt.
- Zusätzlich zu den Inhalten des Moduls steht eine Online App zur Verfügung, mit der grundlegende Aspekte der linearen Regression anhand unterschiedlichen Beispiele erarbeitet werden können (siehe Materialien).


### `r fa("newspaper", fill = "darkgray")`  Lernmodul

 <iframe src="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5236416/index.html" width="100%" height="400" style="border:border:1px solid black;" allow="fullscreen">
</iframe>

- Mouse click inside the slide and press F for the full picture mode
- <a href="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5234058/index.html#/" target="_blank">Or open in a new tab!</a>



### `r fa("question", fill = "darkgray")` Lernzielfrage(n)

- Kannst du erklären was eine lineare Regression macht und wie die Koeffizienten der Regression interpretiert werden?
- Wie werden die vorhergesagte Werte ermittelt? Stichwort KQ Schätzer?
- Was bedeutet ceteris paribus bei multivariaten Analysen?
- Was ist ein spurious confounder?
- Was ist R² und wie wird es interpretiert?

### `r fa("file-pdf", fill = "darkgray")` Materialien

<a href="https://www.studon.fau.de/file3797632_download.html" target="_blank" class="btn btn-secondary"> Slides</a>

<a href="http://edgar-treischl.de:3838/olsGerman/" target="_blank" class="btn btn-primary">Zur OLS App</a>







