---
title: "Session 04"
---

```{r, echo=FALSE}
library(fontawesome)
```


### `r fa("info", fill = "darkgray")` Info

- Session 4 gibt einen Überblick über zentrale Theorien der empirischen Bildungsforschung.
- Hierfür werden zentrale Annahmen und zugrunde liegende Menschenbilder vorgestellt.
- Daneben wird das Rationalitätsprinzip von Karl Popper eingeführt.


### `r fa("newspaper", fill = "darkgray")`  Lernmodul

 <iframe src="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5303086/index.html#/" width="100%" height="400" style="border:border:1px solid black;" allow="fullscreen">
</iframe>

- Mouse click inside the slide and press F for the full picture mode
- <a href="https://www.studon.fau.de/studon/data/StudOn/lm_data/lm_5303086/index.html#/" target="_blank">Or open in a new tab!</a>



### `r fa("question", fill = "darkgray")` Lernzielfrage(n)

- Was ist der Unterschied zwischen Homo Oeconomicus und Homo Sociologicus?
- Warum kann man in diesem Zusammenhang auch von heuristischer Fiktion sprechen?
- Warum ist das Horten von Klopapier nicht als zwingend irrational zu bezeichnen?
- Handelst du nach dem Satisficing Prinzip oder der Maximierung. Kannst du ein Beispiel für beide finden?

### `r fa("file-pdf", fill = "darkgray")` Materialien

<a href="https://www.studon.fau.de/file3797632_download.html" class="btn btn-secondary"> Slides</a>








